# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.5
  - 5.6
  - hhvm

# Commands to be run before your environment runs.
before_script:
  - php -v
  - mysql -e 'create database homestead;'
  - composer self-update
  - composer install --no-progress --no-interaction
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate:refresh
  - php artisan db:seed
  - php vendor/bin/phpunit --colors --coverage-text

# Commands you want to run that will verify your build.
script: phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
